/**
 * Generate Command
 * 
 * Generates AI-friendly documentation and prompts.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk';
import { generateAIManifest, generateAIPrompt } from 'intent-core';
import { loadConfig } from '../utils/config.js';

interface GenerateOptions {
  config: string;
  output: string;
  component?: string;
  prompt: boolean;
}

export async function generateCommand(options: GenerateOptions): Promise<void> {
  console.log(chalk.blue('Intent'), chalk.gray('generating documentation...\n'));
  
  try {
    const config = await loadConfig(options.config);
    const manifest = generateAIManifest(config);
    
    await fs.mkdir(options.output, { recursive: true });
    
    if (options.prompt) {
      // Generate AI prompt for Cursor/Claude
      const prompt = generateAIPrompt(manifest, {
        component: options.component,
      });
      
      const outputPath = path.join(options.output, 'ai-prompt.md');
      await fs.writeFile(outputPath, prompt);
      
      console.log(chalk.green('✓'), 'Generated AI prompt:', chalk.cyan(outputPath));
      console.log();
      console.log(chalk.gray('Copy this file to your .cursorrules or paste into Claude:'));
      console.log(chalk.cyan(`  cat ${outputPath} | pbcopy`));
      
    } else if (options.component) {
      // Generate docs for specific component
      const component = manifest.components.find(c => c.name === options.component);
      
      if (!component) {
        console.log(chalk.red('Error:'), `Component "${options.component}" not found`);
        console.log();
        console.log('Available components:');
        for (const c of manifest.components) {
          console.log(`  - ${chalk.cyan(c.name)}`);
        }
        process.exit(1);
      }
      
      const docs = generateComponentDocs(component);
      const outputPath = path.join(options.output, `${options.component.toLowerCase()}.md`);
      await fs.writeFile(outputPath, docs);
      
      console.log(chalk.green('✓'), 'Generated component docs:', chalk.cyan(outputPath));
      console.log();
      console.log(docs);
      
    } else {
      // Generate full manifest
      const outputPath = path.join(options.output, 'ai-manifest.json');
      await fs.writeFile(outputPath, JSON.stringify(manifest, null, 2));
      
      console.log(chalk.green('✓'), 'Generated AI manifest:', chalk.cyan(outputPath));
      console.log();
      console.log('Components:');
      for (const component of manifest.components) {
        console.log(`  ${chalk.cyan(component.name)}: ${component.description.slice(0, 60)}...`);
      }
      
      // Also generate prompt
      const promptPath = path.join(options.output, 'ai-prompt.md');
      await fs.writeFile(promptPath, generateAIPrompt(manifest));
      console.log();
      console.log(chalk.green('✓'), 'Generated AI prompt:', chalk.cyan(promptPath));
    }
  } catch (error) {
    console.error(chalk.red('Error:'), error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

function generateComponentDocs(component: import('intent-core').ComponentSchemaForAI): string {
  const lines: string[] = [];
  
  lines.push(`# ${component.name}`);
  lines.push('');
  lines.push(component.description);
  lines.push('');
  
  lines.push('## Properties');
  lines.push('');
  
  for (const prop of component.properties) {
    lines.push(`### \`${prop.name}\``);
    lines.push('');
    lines.push(`- **Type:** ${prop.type}`);
    
    if (prop.values) {
      lines.push(`- **Values:** ${prop.values.map(v => `\`${v}\``).join(', ')}`);
    }
    
    lines.push(`- **Required:** ${prop.required ? 'Yes' : 'No'}`);
    
    if (prop.default !== undefined) {
      lines.push(`- **Default:** \`${JSON.stringify(prop.default)}\``);
    }
    
    if (prop.description) {
      lines.push(`- **Description:** ${prop.description}`);
    }
    
    lines.push('');
  }
  
  if (component.constraints.length > 0) {
    lines.push('## Constraints');
    lines.push('');
    
    for (const constraint of component.constraints) {
      lines.push(`- ${constraint}`);
    }
    
    lines.push('');
  }
  
  lines.push('## Examples');
  lines.push('');
  
  lines.push('### Valid Usage');
  lines.push('');
  
  for (const example of component.examples.valid) {
    lines.push('```tsx');
    lines.push(example);
    lines.push('```');
    lines.push('');
  }
  
  if (component.examples.invalid.length > 0) {
    lines.push('### Invalid Usage (Avoid These)');
    lines.push('');
    
    for (const example of component.examples.invalid) {
      lines.push('```tsx');
      lines.push(example);
      lines.push('```');
      lines.push('');
    }
  }
  
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Intent CLI*');
  
  return lines.join('\n');
}
