import { defineSystem, defineComponent, prop, when } from 'intent-core';

export default defineSystem({
    name: 'IntentWebsite',
    version: '1.0.0',

    tokens: {
        color: {
            'brand-primary': '#6366F1',
            'brand-primary-hover': '#4F46E5',
            'brand-secondary': '#8B5CF6',
            'brand-gradient-start': '#6366F1',
            'brand-gradient-end': '#EC4899',
            'feedback-success': '#10B981',
            'feedback-warning': '#F59E0B',
            'feedback-error': '#EF4444',
            'feedback-info': '#3B82F6',
            'surface-default': '#FFFFFF',
            'surface-elevated': '#FFFFFF',
            'surface-subtle': '#F8FAFC',
            'surface-inverse': '#0F172A',
            'text-default': '#0F172A',
            'text-subtle': '#64748B',
            'text-inverse': '#FFFFFF',
            'text-muted': '#94A3B8',
            'border-default': '#E2E8F0',
            'border-subtle': '#F1F5F9',
        },
        space: {
            'none': '0',
            'tight': '4px',
            'compact': '8px',
            'normal': '12px',
            'relaxed': '16px',
            'loose': '24px',
            'xl': '32px',
            'xxl': '48px',
            'xxxl': '64px',
        },
        elevation: {
            'none': '0',
            'low': '0 1px 3px rgba(0,0,0,0.08)',
            'medium': '0 4px 6px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.03)',
            'high': '0 10px 15px rgba(0,0,0,0.05), 0 4px 6px rgba(0,0,0,0.02)',
            'highest': '0 20px 25px rgba(0,0,0,0.1), 0 10px 10px rgba(0,0,0,0.04)',
        },
        radius: {
            'none': '0',
            'sm': '4px',
            'md': '8px',
            'lg': '12px',
            'xl': '16px',
            'full': '9999px',
        },
        typography: {
            'font-sans': "'Inter', system-ui, -apple-system, sans-serif",
            'font-mono': "'JetBrains Mono', ui-monospace, monospace",
            'size-xs': '12px',
            'size-sm': '14px',
            'size-md': '16px',
            'size-lg': '18px',
            'size-xl': '20px',
            'size-2xl': '24px',
            'size-3xl': '30px',
            'size-4xl': '36px',
            'weight-normal': '400',
            'weight-medium': '500',
            'weight-semibold': '600',
            'weight-bold': '700',
            'leading-tight': '1.25',
            'leading-normal': '1.5',
            'leading-relaxed': '1.75',
        },
    },

    darkTokens: {
        color: {
            'brand-primary': '#818CF8',
            'brand-primary-hover': '#6366F1',
            'brand-secondary': '#A78BFA',
            'brand-gradient-start': '#818CF8',
            'brand-gradient-end': '#F472B6',
            'feedback-success': '#34D399',
            'feedback-warning': '#FBBF24',
            'feedback-error': '#F87171',
            'feedback-info': '#60A5FA',
            'surface-default': '#0F172A',
            'surface-elevated': '#1E293B',
            'surface-subtle': '#1E293B',
            'surface-inverse': '#F8FAFC',
            'text-default': '#F1F5F9',
            'text-subtle': '#94A3B8',
            'text-inverse': '#0F172A',
            'text-muted': '#64748B',
            'border-default': '#334155',
            'border-subtle': '#1E293B',
        },
    },

    components: {
        Button: defineComponent({
            name: 'Button',
            description: 'Interactive button element',
            properties: {
                importance: prop.enum(['primary', 'secondary', 'ghost', 'danger'], { required: true }),
                size: prop.enum(['sm', 'md', 'lg'], { default: 'md' }),
                state: prop.enum(['default', 'hover', 'active', 'disabled'], { default: 'default' }),
            },
            constraints: [
                when({ importance: 'ghost' }).forbid(['state'], 'Ghost buttons cannot have a disabled state'),
                when({ importance: 'danger' }).require({ size: ['md', 'lg'] }, 'Danger actions require larger touch targets'),
            ],
            mappings: {
                'importance=primary': { background: 'brand-primary', color: 'text-inverse', border: 'none' },
                'importance=secondary': { background: 'transparent', color: 'brand-primary', border: '1px solid border-default' },
                'importance=ghost': { background: 'transparent', color: 'brand-primary', border: 'none' },
                'importance=danger': { background: 'feedback-error', color: 'text-inverse', border: 'none' },
                'size=sm': { padding: 'tight compact', fontSize: 'size-sm' },
                'size=md': { padding: 'compact relaxed', fontSize: 'size-md' },
                'size=lg': { padding: 'normal loose', fontSize: 'size-lg' },
            },
            baseStyles: {
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 'weight-medium',
                borderRadius: 'radius-md',
                cursor: 'pointer',
                transition: 'all 0.15s ease',
                whiteSpace: 'nowrap',
            },
        }),

        Stack: defineComponent({
            name: 'Stack',
            description: 'Layout component for distributing children along an axis',
            properties: {
                direction: prop.enum(['row', 'column'], { default: 'column' }),
                gap: prop.enum(['none', 'tight', 'compact', 'normal', 'relaxed', 'loose'], { default: 'normal' }),
                align: prop.enum(['start', 'center', 'end', 'stretch'], { default: 'stretch' }),
                justify: prop.enum(['start', 'center', 'end', 'between', 'around'], { default: 'start' }),
            },
            constraints: [],
            mappings: {
                'direction=row': { flexDirection: 'row' },
                'direction=column': { flexDirection: 'column' },
                'gap=none': { gap: 'none' },
                'gap=tight': { gap: 'tight' },
                'gap=compact': { gap: 'compact' },
                'gap=normal': { gap: 'normal' },
                'gap=relaxed': { gap: 'relaxed' },
                'gap=loose': { gap: 'loose' },
                'align=start': { alignItems: 'flex-start' },
                'align=center': { alignItems: 'center' },
                'align=end': { alignItems: 'flex-end' },
                'align=stretch': { alignItems: 'stretch' },
                'justify=start': { justifyContent: 'flex-start' },
                'justify=center': { justifyContent: 'center' },
                'justify=end': { justifyContent: 'flex-end' },
                'justify=between': { justifyContent: 'space-between' },
                'justify=around': { justifyContent: 'space-around' },
            },
            baseStyles: {
                display: 'flex',
            },
        }),

        Surface: defineComponent({
            name: 'Surface',
            description: 'Container providing visual elevation and background treatment',
            properties: {
                elevation: prop.enum(['none', 'low', 'medium', 'high'], { default: 'none' }),
                padding: prop.enum(['none', 'tight', 'compact', 'normal', 'relaxed', 'loose'], { default: 'none' }),
                background: prop.enum(['default', 'subtle', 'elevated', 'inverse'], { default: 'default' }),
                radius: prop.enum(['none', 'sm', 'md', 'lg'], { default: 'none' }),
            },
            constraints: [
                when({ background: 'inverse' }).require({ elevation: ['medium', 'high'] }, 'Inverse backgrounds need elevation'),
            ],
            mappings: {
                'elevation=none': { boxShadow: 'elevation-none' },
                'elevation=low': { boxShadow: 'elevation-low' },
                'elevation=medium': { boxShadow: 'elevation-medium' },
                'elevation=high': { boxShadow: 'elevation-high' },
                'padding=none': { padding: 'none' },
                'padding=tight': { padding: 'tight' },
                'padding=compact': { padding: 'compact' },
                'padding=normal': { padding: 'normal' },
                'padding=relaxed': { padding: 'relaxed' },
                'padding=loose': { padding: 'loose' },
                'background=default': { background: 'surface-default' },
                'background=subtle': { background: 'surface-subtle' },
                'background=elevated': { background: 'surface-elevated' },
                'background=inverse': { background: 'surface-inverse' },
                'radius=none': { borderRadius: 'radius-none' },
                'radius=sm': { borderRadius: 'radius-sm' },
                'radius=md': { borderRadius: 'radius-md' },
                'radius=lg': { borderRadius: 'radius-lg' },
            },
            baseStyles: {
                border: '1px solid border-default',
            },
        }),

        Text: defineComponent({
            name: 'Text',
            description: 'Typography component for displaying text',
            properties: {
                size: prop.enum(['xs', 'sm', 'md', 'lg', 'xl', '2xl'], { default: 'md' }),
                weight: prop.enum(['normal', 'medium', 'semibold', 'bold'], { default: 'normal' }),
                color: prop.enum(['default', 'subtle', 'muted', 'inverse', 'brand'], { default: 'default' }),
                align: prop.enum(['left', 'center', 'right'], { default: 'left' }),
            },
            constraints: [],
            mappings: {
                'size=xs': { fontSize: 'size-xs', lineHeight: 'leading-normal' },
                'size=sm': { fontSize: 'size-sm', lineHeight: 'leading-normal' },
                'size=md': { fontSize: 'size-md', lineHeight: 'leading-normal' },
                'size=lg': { fontSize: 'size-lg', lineHeight: 'leading-relaxed' },
                'size=xl': { fontSize: 'size-xl', lineHeight: 'leading-relaxed' },
                'size=2xl': { fontSize: 'size-2xl', lineHeight: 'leading-tight' },
                'weight=normal': { fontWeight: 'weight-normal' },
                'weight=medium': { fontWeight: 'weight-medium' },
                'weight=semibold': { fontWeight: 'weight-semibold' },
                'weight=bold': { fontWeight: 'weight-bold' },
                'color=default': { color: 'text-default' },
                'color=subtle': { color: 'text-subtle' },
                'color=muted': { color: 'text-muted' },
                'color=inverse': { color: 'text-inverse' },
                'color=brand': { color: 'brand-primary' },
            },
            baseStyles: {
                fontFamily: 'font-sans',
                margin: '0',
            },
        }),

        Badge: defineComponent({
            name: 'Badge',
            description: 'Small label for displaying status or category',
            properties: {
                importance: prop.enum(['default', 'primary', 'success', 'warning', 'error'], { default: 'default' }),
                size: prop.enum(['sm', 'md'], { default: 'sm' }),
            },
            constraints: [],
            mappings: {
                'importance=default': { background: 'surface-subtle', color: 'text-subtle' },
                'importance=primary': { background: 'brand-primary', color: 'text-inverse' },
                'importance=success': { background: 'feedback-success', color: 'text-inverse' },
                'importance=warning': { background: 'feedback-warning', color: 'text-inverse' },
                'importance=error': { background: 'feedback-error', color: 'text-inverse' },
                'size=sm': { padding: 'tight compact', fontSize: 'size-xs' },
                'size=md': { padding: 'compact normal', fontSize: 'size-sm' },
            },
            baseStyles: {
                display: 'inline-flex',
                alignItems: 'center',
                borderRadius: 'radius-full',
                fontWeight: 'weight-medium',
            },
        }),
    },

    settings: {
        cssPrefix: 'intent',
        generateCSSVariables: true,
        strictMode: true,
    },
});
